name = "server"
pages_build_output_dir = "./dist"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV"
id = "3c3cd6d35c2e43e8bf6b3e3973159790"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "web-page-shelf-dev"
database_id = "ddc7b449-780b-43d9-9920-d7dcfde2407c"

# [ai]
# binding = "AI"
